# Services (Containers)
services:
  mongodb-container:
    image: 'mongo'
    volumes:
      - job-portal-db:/data/db # Named volume
    ports:
      - '27018:27017'
    env_file:
      - ./backend/.env

  job-portal-backend-container:
    build:
      context: ./backend
      dockerfile: Dockerfile

    ports:
      - '5000:5000'

    volumes:
      - ./backend:/app # Bind mount
      - /app/node_modules # Anonymous volume (Protect node_modules)

    env_file:
      - ./backend/.env

    depends_on:
      - mongodb-container

  job-portal-frontend-container:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    ports:
      - '5173:5173'

    volumes:
      - ./frontend:/app # Bind mount

    depends_on:
      - job-portal-backend-container

# List Named volumes
volumes:
  job-portal-db:
